# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-test',
                'doc_host': 'https://Dakini.github.io',
                'git_url': 'https://github.com/Dakini/test-test',
                'lib_path': 'test_test'},
  'syms': {'test_test.core': {'test_test.core.foo': ('core.html#foo', 'test_test/core.py')}}}